apiVersion: v1
kind: Service
metadata:
  name: known-event-ui
  namespace: default
spec:
  selector:
    app: known-event-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
